services:
  metronome:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /run/host-services/ssh-auth.sock:/ssh-agent
    environment:
      - CHOKIDAR_USEPOLLING=true
      - GIT_USER_NAME=${GIT_USER_NAME}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL}
      - SSH_AUTH_SOCK=/ssh-agent